services:
  # ======================
  # Backend (FastAPI + Gunicorn)
  # ======================
  - type: web
    name: liverguardian-backend
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

  # ======================
  # Frontend (React static site)
  # ======================
  - type: static
    name: liverguardian-frontend
    branch: main
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: ${liverguardian-backend.url}
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
